# Generated by Django 2.1.2 on 2018-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement_type', models.CharField(help_text="Saisir un type d'emplacement", max_length=200)),
                ('emplacement_price_a_day', models.CharField(help_text="Saisir le prix de l'emplacement à la journée", max_length=10)),
                ('emplacement_summary', models.CharField(help_text="Saisir un résumé de l'emplacement", max_length=2000)),
            ],
        ),
    ]
