# Generated by Django 2.1.2 on 2018-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title1', models.CharField(help_text='Le premier titre du header', max_length=40)),
                ('header_title2', models.CharField(help_text='Le deuxième titre du header', max_length=30)),
                ('header_summary', models.CharField(help_text='Le resumé du header (250 caractères conseillé)', max_length=2000)),
                ('features1_1_title', models.CharField(help_text='Le titre de la feature 1 (bloc 1)', max_length=40)),
                ('features1_1_text', models.CharField(help_text='Le texte de la feature 1 (bloc 1)', max_length=40)),
                ('features1_2_title', models.CharField(help_text='Le titre de la feature 2 (bloc 1)', max_length=40)),
                ('features1_2_text', models.CharField(help_text='Le texte de la feature 2 (bloc 1)', max_length=40)),
                ('features1_3_title', models.CharField(help_text='Le titre de la feature 3 (bloc 1)', max_length=40)),
                ('features1_3_text', models.CharField(help_text='Le texte de la feature 3 (bloc 1)', max_length=40)),
                ('features1_4_title', models.CharField(help_text='Le titre de la feature 4 (bloc 1)', max_length=40)),
                ('features1_4_text', models.CharField(help_text='Le texte de la feature 4 (bloc 1)', max_length=40)),
                ('features2_1_title', models.CharField(help_text='Le titre de la feature 1 (bloc 2)', max_length=40)),
                ('features2_1_text', models.CharField(help_text='Le texte de la feature 1 (bloc 2)', max_length=40)),
                ('features2_2_title', models.CharField(help_text='Le titre de la feature 2 (bloc 2)', max_length=40)),
                ('features2_2_text', models.CharField(help_text='Le texte de la feature 2 (bloc 2)', max_length=40)),
                ('features2_3_title', models.CharField(help_text='Le titre de la feature 3 (bloc 2)', max_length=40)),
                ('features2_3_text', models.CharField(help_text='Le texte de la feature 3 (bloc 2)', max_length=40)),
                ('features2_4_title', models.CharField(help_text='Le titre de la feature 4 (bloc 2)', max_length=40)),
                ('features2_4_text', models.CharField(help_text='Le texte de la feature 4 (bloc 2)', max_length=40)),
                ('features2_5_title', models.CharField(help_text='Le titre de la feature 4 (bloc 2)', max_length=40)),
                ('features2_5_text', models.CharField(help_text='Le texte de la feature 4 (bloc 2)', max_length=40)),
                ('citation_title', models.CharField(help_text='Le titre de la citation', max_length=40)),
                ('citation_auteur', models.CharField(help_text="L'auteur de la citation", max_length=40)),
                ('contact_titre', models.CharField(help_text='Le titre du formulaire de contact', max_length=40)),
                ('contact_texte', models.CharField(help_text='Le texte du formulaire de contact', max_length=40)),
                ('adress', models.CharField(help_text="L'adresse du formulaire de contact", max_length=40)),
                ('email', models.CharField(help_text="L'email du formulaire de contact", max_length=40)),
                ('phone', models.CharField(help_text='Le numéro de téléphone du formulaire de contact', max_length=40)),
                ('email_receptrice', models.CharField(help_text="L'adresse mail sur laquel vous resevrez les mails des visiteurs", max_length=40)),
            ],
        ),
    ]
