# Generated by Django 2.1.2 on 2018-10-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='email_receptrice',
        ),
    ]
