# Generated by Django 2.1.2 on 2018-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_remove_homepage_email_receptrice'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_button1',
            field=models.CharField(default='BOUTON 1', help_text='Le texte du premier bouton dans le header (celui de gauche)', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_button2',
            field=models.CharField(default='BOUTON 2', help_text='Le texte du deuxieme bouton dans le header (celui de droite)', max_length=20),
        ),
    ]
