# Generated by Django 2.1.2 on 2018-10-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='titrte',
            new_name='titre',
        ),
    ]
